name: Docker build and publish
on:
  push:
    tags:
      - 'code-assistant'
  workflow_run:
    workflows: ["Release on Version Change"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Docker build and publish
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version number
        id: get_version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | sed 's/version = "//g' | sed 's/"//g')
          echo "VERSION=$VERSION" > $GITHUB_ENV

      - name: Build and push multi-platform Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            phact/code-assistant:${{ env.VERSION }}
            phact/code-assistant:latest
